version: '3.9'

networks:
  net-ws-sql:
    driver: bridge

services:

  turbo-db:
    image: postgres:alpine
    container_name: turbo-db
    restart: on-failure
    networks:
      - net-ws-sql
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME} 

  turbo-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: turbo-ws
    container_name: turbo-migrate
    restart: on-failure
    depends_on:
      - turbo-db
    networks:
      - net-ws-sql
    command: ["npx", "typeorm", "migration:run", "-d", "./database.js"]
    env_file:
      - .env
    environment: 
      DB_ADDRESS: turbo-db

  turbo-ws:
    image: turbo-ws
    container_name: turbo-ws
    restart: on-failure
    depends_on:
      - turbo-migrate
      - turbo-db
    networks:
      - net-ws-sql
    volumes:
      - ${PROJECTS_PATH}:/turboGis/projects
    env_file:
      - .env
    environment: 
      DB_ADDRESS: turbo-db
      PYTHON_PATH: python3
      QGIS_PATH: /usr/share/qgis/

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: turbo-nginx
    container_name: turbo-nginx
    restart: on-failure
    networks:
      - net-ws-sql
    ports:
      - 443:443
    volumes:
      - ${CERTIFICATES_PATH}:/certificates
    env_file:
      - .env